services:
  bfg-foodchain-webapp:
    container_name: foodchain-webapp-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.docker
    ports:
      - 8080:${PORT}
