# Generated by Django 5.0 on 2024-09-21 08:25

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="iron",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Iron (milligrams)",
            ),
        ),
        migrations.AddField(
            model_name="foodcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.utils.image_upload_path
            ),
        ),
    ]
