# Generated by Django 5.0 on 2024-09-22 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_notification_mobile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FoodReplacement",
        ),
    ]
